import sanitizeHtml from "sanitize-html";

const allowedTags = sanitizeHtml.defaults.allowedTags.concat([
  "article",
  "aside",
  "blockquote",
  "br",
  "button",
  "code",
  "figure",
  "figcaption",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hr",
  "img",
  "input",
  "label",
  "li",
  "main",
  "nav",
  "ol",
  "option",
  "p",
  "picture",
  "pre",
  "section",
  "select",
  "small",
  "source",
  "s",
  "strong",
  "sub",
  "sup",
  "ul",
  "textarea",
]);

const sharedAttributes = [
  "class",
  "id",
  "title",
  "role",
  "tabindex",
  "aria-label",
  "aria-hidden",
  "aria-controls",
  "aria-expanded",
  "data-target",
  "data-text",
  "data-bs-dismiss",
  "data-bs-target",
  "data-bs-toggle",
];

const sanitizeConfig: sanitizeHtml.IOptions = {
  allowedTags,
  allowedAttributes: {
    "*": sharedAttributes,
    a: [...sharedAttributes, "href", "name", "target", "rel"],
    button: [...sharedAttributes, "type"],
    code: [...sharedAttributes],
    form: [...sharedAttributes, "action", "method"],
    img: [...sharedAttributes, "src", "srcset", "alt", "width", "height", "loading"],
    input: [
      ...sharedAttributes,
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "disabled",
      "readonly",
      "required",
      "min",
      "max",
      "step",
    ],
    label: [...sharedAttributes, "for"],
    option: [...sharedAttributes, "selected", "value"],
    select: [...sharedAttributes, "name", "multiple", "required"],
    source: [...sharedAttributes, "srcset", "type", "media"],
    textarea: [...sharedAttributes, "name", "rows", "cols", "placeholder", "required"],
  },
  allowedSchemes: ["http", "https", "mailto", "tel", "data"],
  allowProtocolRelative: false,
  transformTags: {
    a: sanitizeHtml.simpleTransform("a", {
      rel: "noopener noreferrer",
    }),
  },
};

export function sanitizeRichHtml(value: string) {
  return sanitizeHtml(value, sanitizeConfig);
}
