import type { PricingCategory, PricingSection, ServiceOffering } from "@/modules/pricing/types";

function createServiceOffering(input: {
  id: string;
  categoryId: string;
  pricingSectionId: string;
  slug: string;
  title: string;
  priceAmount: number;
  subtitle?: string;
  durationMinutes?: number;
  featureBullets: string[];
  ctaLabel: string;
  sortOrder: number;
}): ServiceOffering {
  const priceLabel = Number.isInteger(input.priceAmount)
    ? `${input.priceAmount} lei`
    : `${input.priceAmount.toFixed(2)} lei`;

  return {
    id: input.id,
    categoryId: input.categoryId,
    categoryKey: input.categoryId,
    pricingSectionId: input.pricingSectionId,
    title: input.title,
    priceLabel,
    priceAmount: input.priceAmount,
    currencyCode: "RON",
    subtitle: input.subtitle,
    description: input.featureBullets.join(" | "),
    featureBullets: input.featureBullets,
    features: input.featureBullets,
    durationMinutes: input.durationMinutes,
    ctaLabel: input.ctaLabel,
    slug: input.slug,
    visible: true,
    bookable: true,
    sortOrder: input.sortOrder,
  };
}

export const legacyServiceCategories: PricingCategory[] = [
  {
    id: "diagnoza-celulara",
    slug: "diagnoza-celulara",
    name: "Diagnoza Celulară",
    description: "Descoperă și înțelege mai bine sănătatea ta prin analiză celulară.",
    visible: true,
    sortOrder: 1,
  },
  {
    id: "nutritie",
    slug: "nutritie",
    name: "Nutriție",
    description: "Construiește un stil de viață sănătos prin nutriție echilibrată.",
    visible: true,
    sortOrder: 2,
  },
  {
    id: "terapie-shockwave",
    slug: "terapie-shockwave",
    name: "Terapie Shockwave",
    description: "Pachete pentru terapia cu unde de șoc",
    visible: true,
    sortOrder: 3,
  },
];

export const legacyPricingSections: PricingSection[] = [
  {
    id: "diagnoza-celulara-default",
    categoryId: "diagnoza-celulara",
    slug: "default",
    visible: true,
    sortOrder: 1,
  },
  {
    id: "nutritie-default",
    categoryId: "nutritie",
    slug: "default",
    visible: true,
    sortOrder: 1,
  },
  {
    id: "terapie-shockwave-default",
    categoryId: "terapie-shockwave",
    slug: "default",
    visible: true,
    sortOrder: 1,
  },
];

export const legacyServiceOfferings: ServiceOffering[] = [
  createServiceOffering({
    id: "diagnoza-globala",
    categoryId: "diagnoza-celulara",
    pricingSectionId: "diagnoza-celulara-default",
    slug: "sedinta-de-diagnoza-globala",
    title: "Ședință de Diagnoză Globală",
    priceAmount: 900,
    subtitle: "Durata 90 min",
    durationMinutes: 90,
    featureBullets: [
      "Măsurarea stării inițiale a funcțiilor organelor și sistemelor corpului",
      "Tratament",
      "Evaluarea răspunsului organismului la tratamentul aplicat",
    ],
    ctaLabel: "Programează",
    sortOrder: 1,
  }),
  createServiceOffering({
    id: "diagnoza-intermediara",
    categoryId: "diagnoza-celulara",
    pricingSectionId: "diagnoza-celulara-default",
    slug: "sedinta-diagnoza-intermediara",
    title: "Ședință Diagnoză Intermediară",
    priceAmount: 750,
    featureBullets: [
      "Este folosită la jumătatea programelor de tratament de 6–12 ședințe pentru evaluarea rezultatelor intermediare",
    ],
    ctaLabel: "Programează",
    sortOrder: 2,
  }),
  createServiceOffering({
    id: "tratament-mitoplus",
    categoryId: "diagnoza-celulara",
    pricingSectionId: "diagnoza-celulara-default",
    slug: "sedinta-tratament-mitoplus",
    title: "Ședință Tratament Mitoplus",
    priceAmount: 350,
    featureBullets: [
      "Tratament specializat în cazul unei patologii cunoscute, după efectuarea diagnozei globale și verificarea stării funcțiilor organelor și a sistemelor corpului",
    ],
    ctaLabel: "Programează",
    sortOrder: 3,
  }),
  createServiceOffering({
    id: "program-complex-8-sedinte",
    categoryId: "diagnoza-celulara",
    pricingSectionId: "diagnoza-celulara-default",
    slug: "programe-complexe-de-tratament-8-sedinte",
    title: "Programe complexe de tratament",
    priceAmount: 2900,
    subtitle: "8 ședințe + 1 diagnoză intermediară",
    featureBullets: [
      "Se alege programul necesar după efectuarea diagnozei globale și verificarea stării funcțiilor organelor și a sistemelor corpului",
    ],
    ctaLabel: "Programează",
    sortOrder: 4,
  }),
  createServiceOffering({
    id: "program-complex-12",
    categoryId: "diagnoza-celulara",
    pricingSectionId: "diagnoza-celulara-default",
    slug: "programe-complexe-de-tratament-12-sedinte",
    title: "Programe complexe de tratament",
    priceAmount: 4400,
    subtitle: "12 ședințe + 2 diagnoze intermediare",
    featureBullets: [
      "Se alege programul necesar după efectuarea diagnozei globale și verificarea stării funcțiilor organelor și a sistemelor corpului",
    ],
    ctaLabel: "Programează",
    sortOrder: 5,
  }),
  createServiceOffering({
    id: "recalibrarea-raspunsului-hormonal",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "recalibrarea-raspunsului-hormonal-program-de-nutritie-online",
    title: "Recalibrarea Răspunsului Hormonal - program de nutritie online",
    priceAmount: 2300,
    subtitle: "4 luni",
    durationMinutes: 45,
    featureBullets: [
      "Online",
      "8 ședințe individuale prin Zoom, WhatsApp sau telefon, stabilite de comun acord la interval de 2 săptămâni una de cealaltă.",
      "Suport prin e-mail nelimitat – răspunsuri și întrebări despre orice problemă legată de nutriție.",
      "Suport de program: fișă jurnal de nutriție, fișă grupe alimentare.",
    ],
    ctaLabel: "Programează",
    sortOrder: 1,
  }),
  createServiceOffering({
    id: "evaluare-globala",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "evaluare-globala-diagnoza-celulara-analiza-nutritionala-complexa",
    title: "Evaluare globală diagnoză celulară + analiză nutrițională complexă",
    priceAmount: 1200,
    subtitle: "Ședință (120 min)",
    durationMinutes: 120,
    featureBullets: [
      "Diagnoză globală cu detectarea deficiențelor de funcționare celulară",
      "Evaluare nutrițională / chestionar",
      "Verificare compoziție corporală – interpretare",
      "Verificare și interpretare analize de laborator",
    ],
    ctaLabel: "Programează",
    sortOrder: 2,
  }),
  createServiceOffering({
    id: "nutritie-clinica",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "nutritie-clinica",
    title: "Nutriție clinică",
    priceAmount: 350,
    subtitle: "Ședință",
    durationMinutes: 45,
    featureBullets: [
      "Evaluare nutrițională / chestionar",
      "Verificare și interpretare analize de laborator",
      "Analiză compoziție corporală – interpretare",
      "Analiză comportament alimentar",
      "Stabilire obiective",
      "Personalizare plan alimentar / patologie",
    ],
    ctaLabel: "Programează",
    sortOrder: 3,
  }),
  createServiceOffering({
    id: "nutritie-sportiva",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "nutritie-sportiva",
    title: "Nutriție sportivă",
    priceAmount: 350,
    subtitle: "Ședință",
    durationMinutes: 45,
    featureBullets: [
      "Evaluare nutrițională / chestionar",
      "Verificare și interpretare analize de laborator",
      "Analiză compoziție corporală – interpretare",
      "Analiză comportament alimentar",
      "Stabilire obiective",
      "Personalizare plan alimentar / sport practicat",
      "Schemă personalizată de administrare suplimente",
    ],
    ctaLabel: "Programează",
    sortOrder: 4,
  }),
  createServiceOffering({
    id: "nutritie-la-cabinet",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "nutritie-la-cabinet-recalibrarea-raspunsului-hormonal",
    title: "Nutriție la cabinet – Recalibrarea Răspunsului Hormonal",
    priceAmount: 350,
    subtitle: "Ședință",
    durationMinutes: 45,
    featureBullets: [
      "Evaluare nutrițională / chestionar",
      "Cântărire, IMC",
      "Verificare compoziție corporală – interpretare",
      "Verificare și interpretare analize de laborator",
      "Explicații despre principiile programului",
      "Stabilire obiective",
      "Personalizare plan alimentar",
      "Fișă jurnal + grupe alimentare + farfurie demonstrativă",
      "Verificare zilnică pe e-mail a jurnalului (2 săptămâni)",
    ],
    ctaLabel: "Programează",
    sortOrder: 5,
  }),
  createServiceOffering({
    id: "detox-fiziologic",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "recalibrarea-raspunsului-hormonal-stimulare-metabolica-detox-fiziologic",
    title: "Recalibrarea Răspunsului Hormonal – Stimulare Metabolică / Detox Fiziologic",
    priceAmount: 3500,
    subtitle: "Program",
    durationMinutes: 45,
    featureBullets: [
      "Program de nutriție pentru slăbire la cabinet",
      "Ședință inițială: evaluare + analize + BIA + diagnoză + stimulare metabolică",
      "6 ședințe nutriție la 2 săptămâni",
      "3 ședințe stimulare metabolică la 4 săptămâni",
      "Personalizare plan alimentar",
    ],
    ctaLabel: "Programează",
    sortOrder: 6,
  }),
  createServiceOffering({
    id: "diagnoza-metabolism",
    categoryId: "nutritie",
    pricingSectionId: "nutritie-default",
    slug: "diagnoza-stare-de-sanatate-si-sisteme-care-influenteaza-metabolismul",
    title: "Diagnoză stare de sănătate și sisteme care influențează metabolismul",
    priceAmount: 900,
    subtitle: "Ședință (90 min)",
    durationMinutes: 90,
    featureBullets: ["Durata 90 min"],
    ctaLabel: "Programează",
    sortOrder: 7,
  }),
  createServiceOffering({
    id: "sedinta-terapie-shockwave",
    categoryId: "terapie-shockwave",
    pricingSectionId: "terapie-shockwave-default",
    slug: "sedinta-terapie-shockwave",
    title: "Sedinta terapie shockwave",
    priceAmount: 375,
    subtitle: "8–15 min",
    durationMinutes: 15,
    featureBullets: [
      "Aplicare locală unde de șoc",
      "Recomandari post sedinta",
      "Interval recomandat 7-10 zile",
    ],
    ctaLabel: "Programează",
    sortOrder: 1,
  }),
  createServiceOffering({
    id: "pachet-shockwave-start",
    categoryId: "terapie-shockwave",
    pricingSectionId: "terapie-shockwave-default",
    slug: "pachet-shockwave-start",
    title: "Pachet shockwave start",
    priceAmount: 1050,
    subtitle: "3 ședințe",
    featureBullets: [
      "Protocol afectiuni acute: 3 ședințe la 7–10 zile",
      "Re-evaluare scurta la fiecare sedinta",
      "Recomandari post sedinta",
    ],
    ctaLabel: "Programează",
    sortOrder: 2,
  }),
  createServiceOffering({
    id: "pachet-shockwave-intensiv",
    categoryId: "terapie-shockwave",
    pricingSectionId: "terapie-shockwave-default",
    slug: "pachet-shockwave-intensiv",
    title: "Pachet shockwave intensiv",
    priceAmount: 1980,
    subtitle: "6 ședințe",
    featureBullets: [
      "Protocol extins pentru afectiuni cronice",
      "Monitorizare progres (durere, mobilitate)",
      "Recomandari post sedinta",
    ],
    ctaLabel: "Programează",
    sortOrder: 3,
  }),
  createServiceOffering({
    id: "sedinta-shockwave-celulita-o-zona",
    categoryId: "terapie-shockwave",
    pricingSectionId: "terapie-shockwave-default",
    slug: "sedinta-shockwave-celulita-o-zona",
    title: "Sedinta shockwave celulita o zona",
    priceAmount: 550,
    subtitle: "Per zona",
    featureBullets: [
      "Protocol variabil 3-5 sedinte in functie de gradul celulitei",
      "Monitorizare progres",
      "Recomandari post sedinta",
    ],
    ctaLabel: "Programează",
    sortOrder: 4,
  }),
  createServiceOffering({
    id: "sedinta-shockwave-disfunctie-erectila",
    categoryId: "terapie-shockwave",
    pricingSectionId: "terapie-shockwave-default",
    slug: "sedinta-shockwave-disfunctie-erectila-boala-peyronie",
    title: "Sedinta shockwave disfunctie erectila / boala Peyronie",
    priceAmount: 400,
    subtitle: "Per sedinta",
    featureBullets: [
      "Protocol 5-6 sedinte",
      "Monitorizare progres",
      "Recomandari individuale",
    ],
    ctaLabel: "Programează",
    sortOrder: 5,
  }),
  createServiceOffering({
    id: "sedinta-shockwave-contractura-dupuytren",
    categoryId: "terapie-shockwave",
    pricingSectionId: "terapie-shockwave-default",
    slug: "sedinta-shockwave-contractura-dupuytren",
    title: "Sedinta shockwave contractura Dupuytren",
    priceAmount: 400,
    subtitle: "Per sedinta",
    featureBullets: [
      "Protocol 5-6 sedinte",
      "Monitorizare progres",
      "Recomandari individuale",
    ],
    ctaLabel: "Programează",
    sortOrder: 6,
  }),
];
