import "server-only";

export type NutritionQuestionnairePreviewVariant = "default" | "stress";

type PreviewPayload = {
  patientName: string;
  reference: string;
  submittedAt: string;
  payload: Record<string, unknown>;
};

const defaultPreviewPayload = {
  patientName: "Elena Popescu",
  reference: "PREVIEW-AB12",
  submittedAt: "2026-04-15T10:30:00.000Z",
  payload: {
    name: "Elena Popescu",
    age: "34",
    birth_date: "1990-05-14",
    sex: "F",
    marital_status: "Casatorit",
    children: "1",
    height: "168",
    weight: "74",
    ideal_weight: "62",
    "antecedente_familiale[]": ["Cancer", "Boli de inima"],
    antecedente_altele_descriere: "Hipotiroidism matern",
    interventii_boli: "Da",
    interventii_boli_descriere: "Colita ulcerativa diagnosticata in 2021",
    modificari_greutate: "Crestere de 8 kg in ultimii 2 ani.",
    "femeie_menstruatie[]": ["Premenopauza"],
    probleme_sanatate: "Hipotiroidism si oboseala cronica.",
    fumati: "Nu",
    alcool: "Da",
    alcool_cantitate: "1-2 pahare pe saptamana",
    stress_level: "4",
    readiness_level: "3",
    obstacole: "Program de lucru haotic si oboseala.",
    practici_religioase_toggle: "Nu",
    medicamente_radio: "Da",
    "medicamente[]": ["Euthyrox"],
    "medicamente_cantitate[]": ["50 mcg"],
    suplimente_radio: "Da",
    "suplimente[]": ["Vitamina D"],
    "suplimente_cantitate[]": ["2000 UI"],
    activitate_fizica: "Da",
    activitate_frecventa: "3 zile / saptamana",
    activitate_durata: "45 minute / zi",
    activitate_descriere: "Mers rapid si yoga",
    obiective_alimentare: "Sa reduc pofta de dulce si sa slabesc 10 kg.",
    pofta_mancare: "Da",
    pofta_mancare_explicatii: "Mai ales seara.",
    alergii_toggle: "Nu",
    diete_toggle: "Da",
    "diete[]": ["Low carb"],
    "diete_descriere[]": ["Timp de 3 luni"],
    laxative: "Nu",
    fastfood_frecventa: "0-1/luna",
    ora_mic_dejun: "08:30",
    ora_pranz: "13:30",
    ora_cina: "19:30",
    ora_gustari: "11:00, 16:30",
    fluctuatii_greutate: "Da, intre 68 si 78 kg.",
    "declansatori[]": ["Stresul", "Obiceiuri alimentare"],
    mese_pe_zi: "3",
    mese_descriere: "Mic dejun, pranz, cina",
    "alimenteConsumate[]": ["Paste", "Dulciuri"],
    paine: "Paine integrala, 2 felii pe zi.",
    "grasimi[]": ["Unt", "Ulei de masline"],
    "bauturi[]": ["Apa", "Cafea"],
    alcool_frecventa: "2-3/luna",
    "pofte[]": ["Dulciuri", "Paine"],
    "displaceri[]": ["Broccoli"],
    "alimentatie_zi[]": ["Luni", "Marti"],
    "alimentatie_produs[]": ["Omleta cu avocado", "Iaurt cu afine"],
    "alimentatie_cantitate[]": ["250g", "200g"],
    "alimentatie_ora[]": ["08:30", "09:00"],
  } satisfies Record<string, unknown>,
} satisfies PreviewPayload;

const stressPreviewPayload = {
  patientName: "Alexandra Mironescu",
  reference: "PREVIEW-STRESS-98XZ",
  submittedAt: "2026-04-17T08:15:00.000Z",
  payload: {
    name: "Alexandra Mironescu",
    age: "46",
    birth_date: "1979-09-03",
    sex: "F",
    marital_status: "Casatorita",
    children: "2",
    height: "171",
    weight: "92",
    ideal_weight: "68",
    "antecedente_familiale[]": [
      "Diabet zaharat",
      "Cancer",
      "Boli de inima",
      "Hipertensiune",
      "Obezitate",
      "Boli autoimune",
      "Accident vascular cerebral",
    ],
    antecedente_altele_descriere:
      "Istoric matern de hipotiroidism autoimun, osteoporoza dupa menopauza si afectiuni digestive recurente. Pe linie paterna exista sindrom metabolic, hiperuricemie si episoade repetate de boala cardiovasculara.",
    interventii_boli: "Da",
    interventii_boli_descriere:
      "Colecistectomie laparoscopica in 2017, endometrioza diagnosticata in 2019, reflux gastro-esofagian, colon iritabil, steatoza hepatica grad I, episoade recurente de migrena si dureri articulare asociate sedentarismului prelungit.",
    modificari_greutate:
      "Crestere progresiva de aproximativ 18 kg in ultimii 5 ani, cu fluctuatii rapide in perioadele de stres si regres dupa diete restrictive care nu au putut fi sustinute pe termen lung.",
    "femeie_menstruatie[]": [
      "Perimenopauza",
      "Ciclu neregulat",
      "Menstre abundente",
      "Dureri accentuate",
    ],
    femeie_menstruatie_descriere:
      "Simptomele se intensifica in perioada premenstruala, cu retentie de apa, pofta de dulce, insomnie si iritabilitate marcata timp de 4-5 zile.",
    probleme_sanatate:
      "Hipotiroidism subclinic, rezistenta la insulina, sindrom digestiv cu balonare zilnica, oboseala constanta si dificultate in recuperarea dupa perioadele de lucru intens. Se plange si de rigiditate matinala, concentrare slaba si somn fragmentat.",
    fumati: "Nu",
    alcool: "Da",
    alcool_cantitate:
      "2-3 pahare de vin in weekend si consum ocazional la evenimente sociale sau cine de afaceri.",
    stress_level: "5",
    readiness_level: "4",
    obstacole:
      "Programul de lucru foarte imprevizibil, deplasari dese, mese luate in masina sau intre sedinte, lipsa unui ritual constant de somn si tendinta de a compensa emotional cu gustari dulci seara.",
    practici_religioase_toggle: "Da",
    practici_religioase:
      "Post intermitent in anumite perioade religioase; evita anumite combinatii alimentare in familie.",
    medicamente_radio: "Da",
    "medicamente[]": [
      "Euthyrox",
      "Esomeprazol",
      "Magneziu",
      "Vitamina B complex",
      "Progesteron bioidentic",
      "Metformin",
      "Antihistaminic",
      "Probiotic recomandat gastroenterologic",
    ],
    "medicamente_cantitate[]": [
      "75 mcg dimineata",
      "40 mg la nevoie",
      "1 capsula seara",
      "1 comprimat dimineata",
      "conform recomandarii medicului ginecolog",
      "500 mg dupa cina",
      "1 comprimat in sezon alergic",
      "10 zile/luna",
    ],
    suplimente_radio: "Da",
    "suplimente[]": [
      "Vitamina D3",
      "Omega 3",
      "Coenzima Q10",
      "Colagen marin",
      "Inozitol",
      "Zinc",
      "Ashwagandha",
      "Berberina",
      "Electroliti",
    ],
    "suplimente_cantitate[]": [
      "4000 UI",
      "2 capsule / zi",
      "100 mg",
      "10 g",
      "2 plicuri / zi",
      "25 mg",
      "1 capsula seara",
      "500 mg in cure",
      "la antrenamente si in zilele caniculare",
    ],
    activitate_fizica: "Da",
    activitate_frecventa: "4-5 zile / saptamana",
    activitate_durata: "35-60 minute / zi",
    activitate_descriere:
      "Mers alert, pilates, exercitii cu greutatea corpului, bicicleta stationara si sedinte sporadice de kinetoterapie pentru mobilitate si postura.",
    obiective_alimentare:
      "Sa reduca inflamatia si balonarea, sa normalizeze pofta de dulce, sa obtina scadere ponderala sustenabila, sa aiba energie constanta si sa poata mentine un program alimentar coerent inclusiv in deplasari.",
    pofta_mancare: "Da",
    pofta_mancare_explicatii:
      "Pofta de dulce este intensa dupa ora 17:00, mai ales in zilele stresante sau cand sare peste pranz. Exista si perioade cu apetit scazut dimineata si supraalimentare seara.",
    alergii_toggle: "Da",
    "alergii[]": [
      "Lapte de vaca",
      "Gluten",
      "Fructe de mare",
      "Capsuni",
      "Conservanti alimentari",
      "Coloranti artificiali",
    ],
    "alergii_descriere[]": [
      "Balonare, congestie nazala si eruptii dupa consum repetat.",
      "Disconfort abdominal si oboseala dupa mesele bogate in panificatie.",
      "Istoric de reactie cutanata si greata.",
      "Apar pete rosii periorale.",
      "Simte iritatie digestiva si dureri de cap.",
      "Asociaza consumul cu migrene si agitatie.",
    ],
    diete_toggle: "Da",
    "diete[]": [
      "Low carb",
      "Post intermitent 16:8",
      "Dieta hiperproteica",
      "Dieta disociata",
      "Plan keto partial",
      "Eliminare gluten/lactate",
    ],
    "diete_descriere[]": [
      "A functionat 2 luni, apoi au aparut pofte intense si oboseala.",
      "A dus la amanarea meselor si episoade de supraalimentare seara.",
      "Greu de sustinut in deplasari si la mesele cu familia.",
      "A incercat-o pentru perioade scurte fara rezultate stabile.",
      "A fost urmata neuniform si a accentuat constipatia.",
      "A redus balonarea, dar nu a fost mentinuta consistent.",
    ],
    laxative: "Da",
    laxative_explicatii:
      "A folosit ceaiuri laxative si perioade de restrictie severa dupa episoade de supraalimentare in trecut, fara utilizare recenta constanta.",
    fastfood_frecventa: "2-3 ori / saptamana in perioade aglomerate",
    ora_mic_dejun: "08:00-09:30",
    ora_pranz: "13:00-15:00",
    ora_cina: "19:30-21:30",
    ora_gustari: "11:00, 17:30, uneori 22:00",
    fluctuatii_greutate:
      "Variatii intre 74 kg si 94 kg in ultimii 10 ani, cu recastig rapid dupa perioadele restrictive.",
    "declansatori[]": [
      "Stres profesional",
      "Mese neregulate",
      "Lipsa somnului",
      "Pofta emotionala",
      "Sedentarism",
      "Schimbari hormonale",
      "Mese sociale dese",
    ],
    declansatori_altele_text:
      "Lipsa planificarii cumparaturilor, mancatul in masina, calatoriile lungi si senzatia ca trebuie sa termine tot din farfurie.",
    mese_pe_zi: "3 mese principale + 2-3 gustari",
    mese_descriere:
      "Mic dejun tarziu, pranz uneori incomplet, cina bogata si gustari dulci sau sarate in a doua parte a zilei.",
    "alimenteConsumate[]": [
      "Paste cu sos alb",
      "Ciocolata",
      "Produse de patiserie",
      "Pizza",
      "Branzeturi maturate",
      "Chipsuri",
      "Covrigi",
      "Iaurt cu fructe",
      "Biscuiti digestivi",
      "Inghetata",
      "Tort la evenimente",
      "Paine prajita cu unt",
    ],
    paine:
      "Paine integrala sau multicereale, dar in perioade aglomerate consuma si covrigi, lipii sau sandwich-uri comerciale; aproximativ 3-5 portii pe zi.",
    "grasimi[]": [
      "Unt",
      "Ulei de masline",
      "Avocado",
      "Maioneza",
      "Unt de arahide",
      "Seminte",
      "Nuci",
    ],
    "bauturi[]": ["Apa", "Cafea", "Apa minerala", "Ceai", "Vin"],
    bauturi_altele_text:
      "Ocazional bauturi energizante fara zahar si cappuccino cu lapte vegetal indulcit.",
    alcool_frecventa:
      "1-2 seri pe saptamana, mai ales in weekend sau la cine de networking.",
    "pofte[]": ["Dulciuri", "Paine", "Branzeturi", "Saraturi", "Ciocolata"],
    pofte_altele_text:
      "In serile foarte lungi apare pofta de cereal bar, biscuiti sau produse crocante.",
    "displaceri[]": [
      "Ficat",
      "Conopida fiarta",
      "Varza de Bruxelles",
      "Broccoli fiert excesiv",
      "Pește cu gust intens",
      "Organe",
      "Mancare foarte picanta",
      "Texturi gelatinoase",
    ],
    "alimentatie_zi[]": [
      "Luni",
      "Luni",
      "Luni",
      "Luni",
      "Marti",
      "Marti",
      "Marti",
      "Marti",
      "Miercuri",
      "Miercuri",
      "Miercuri",
      "Joi",
      "Joi",
      "Joi",
      "Vineri",
      "Vineri",
      "Vineri",
      "Sambata",
      "Sambata",
      "Duminica",
    ],
    "alimentatie_produs[]": [
      "Cafea cu lapte vegetal si croissant cu unt",
      "Sandwich cu pui, branza si sos",
      "Cappuccino si 2 biscuiti digestivi",
      "Paste cu sos alb, parmesan si focaccia",
      "Omleta cu legume si paine prajita",
      "Salata cu ton, masline si crackers",
      "Ciocolata neagra si mix de nuci",
      "Supa crema si piept de pui cu orez",
      "Iaurt cu fructe si granola",
      "Sushi take-away",
      "Inghetata artizanala",
      "Smoothie cu banana, unt de arahide si fulgi de ovaz",
      "Pizza cu prosciutto",
      "Covrigi cu susan",
      "Briose proteice",
      "Burger cu cartofi wedges",
      "Vin alb si platou de branzeturi",
      "Clatite cu ricotta si miere",
      "Friptura cu piure si salata",
      "Mancare comandata la domiciliu, tip asian bowl",
    ],
    "alimentatie_cantitate[]": [
      "1 cafea + 1 bucata",
      "1 portie mare",
      "1 cafea + 2 bucati",
      "450 g",
      "2 oua + 2 felii paine",
      "1 bol mare",
      "45 g",
      "1 bol + 180 g",
      "250 g",
      "12 bucati",
      "180 g",
      "500 ml",
      "4 felii mari",
      "2 bucati",
      "2 bucati",
      "1 portie mare",
      "2 pahare + 250 g",
      "3 bucati",
      "1 portie mare",
      "1 bol mare",
    ],
    "alimentatie_ora[]": [
      "08:10",
      "13:45",
      "17:20",
      "21:10",
      "08:40",
      "13:15",
      "16:50",
      "20:35",
      "09:00",
      "14:10",
      "21:45",
      "08:15",
      "13:00",
      "17:40",
      "08:30",
      "14:25",
      "21:30",
      "10:00",
      "18:20",
      "20:50",
    ],
  } satisfies Record<string, unknown>,
} satisfies PreviewPayload;

export function normalizeNutritionQuestionnairePreviewVariant(
  variant: string | string[] | undefined,
  fallback: NutritionQuestionnairePreviewVariant = "default",
): NutritionQuestionnairePreviewVariant {
  const normalized = Array.isArray(variant) ? variant[0] : variant;

  return normalized === "stress" || normalized === "default"
    ? normalized
    : fallback;
}

export function getNutritionQuestionnairePreviewData(
  variant: NutritionQuestionnairePreviewVariant = "default",
) {
  return variant === "stress" ? stressPreviewPayload : defaultPreviewPayload;
}
