insert into public.service_categories (id, slug, name, description, sort_order, is_visible)
values
  (
    'diagnoza-celulara',
    'diagnoza-celulara',
    'Diagnoza Celulara',
    'Descopera si intelege mai bine sanatatea ta prin analiza celulara.',
    1,
    true
  ),
  (
    'nutritie',
    'nutritie',
    'Nutritie',
    'Programe personalizate de nutritie, echilibrare hormonala si evaluari complexe.',
    2,
    true
  )
on conflict (id) do update
set slug = excluded.slug,
    name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_visible = excluded.is_visible,
    updated_at = timezone('utc', now());

insert into public.service_offerings (
  id,
  category_id,
  slug,
  name,
  description,
  notes,
  price_amount,
  currency_code,
  duration_minutes,
  is_bookable,
  is_visible,
  sort_order
)
values
  (
    'diagnoza-globala',
    'diagnoza-celulara',
    'sedinta-de-diagnoza-globala',
    'SEDINTA DE DIAGNOZA GLOBALA',
    'Masurarea starii initiale a functiilor organelor si sistemelor corpului | Evaluare energetica celulara si vegetativa | Identificarea dezechilibrelor metabolice importante',
    'Durata 90 min',
    850,
    'RON',
    90,
    true,
    true,
    1
  ),
  (
    'diagnoza-intermediara',
    'diagnoza-celulara',
    'sedinta-diagnoza-intermediara',
    'SEDINTA DIAGNOZA INTERMEDIARA',
    'Evaluarea rezultatelor intermediare in programele de tratament | Monitorizare comparativa fata de diagnosticul initial',
    null,
    700,
    'RON',
    null,
    true,
    true,
    2
  ),
  (
    'tratament-mitoplus',
    'diagnoza-celulara',
    'sedinta-tratament-mitoplus',
    'SEDINTA TRATAMENT MITOPLUS',
    'Tratament specializat dupa evaluarea initiala | Suport pentru patologii cunoscute si dezechilibre metabolice',
    null,
    350,
    'RON',
    30,
    true,
    true,
    3
  ),
  (
    'program-complex-6',
    'diagnoza-celulara',
    'programe-complexe-de-tratament-6',
    'PROGRAME COMPLEXE DE TRATAMENT',
    'Program ales dupa diagnoza globala | 6 sedinte de tratament si reevaluare intermediara',
    '6 Sedinte + 1 Diagnoza Intermediara',
    2300,
    'RON',
    null,
    true,
    true,
    4
  ),
  (
    'program-complex-12',
    'diagnoza-celulara',
    'programe-complexe-de-tratament-12',
    'PROGRAME COMPLEXE DE TRATAMENT',
    'Program extins pentru dezechilibre complexe | 12 sedinte si doua reevaluari intermediare',
    '12 Sedinte + 2 Diagnoza Intermediara',
    4300,
    'RON',
    null,
    true,
    true,
    5
  ),
  (
    'recalibrarea-raspunsului-hormonal',
    'nutritie',
    'recalibrarea-raspunsului-hormonal',
    'RECALIBRAREA RASPUNSULUI HORMONAL',
    'Online | Consiliere personalizata pe termen lung | Program de nutritie si reglare hormonala',
    '4 Luni',
    2200,
    'RON',
    null,
    true,
    true,
    1
  ),
  (
    'evaluare-globala',
    'nutritie',
    'evaluare-globala-diagnoza-celulara-analiza-nutritionala',
    'Evaluare globala diagnoza celulara + analiza nutritionala complexa',
    'Durata 120 min | Verificare compozitie corporala | Interpretare analize de laborator | Evaluare nutritionala complexa',
    'Sedinta',
    1100,
    'RON',
    120,
    true,
    true,
    2
  ),
  (
    'nutritie-clinica',
    'nutritie',
    'nutritie-clinica',
    'Nutritie clinica',
    'Evaluare nutritionala si chestionar | Verificare si interpretare analize de laborator | Plan alimentar personalizat',
    'Sedinta',
    350,
    'RON',
    60,
    true,
    true,
    3
  ),
  (
    'nutritie-sportiva',
    'nutritie',
    'nutritie-sportiva',
    'Nutritie sportiva',
    'Analiza compozitiei corporale | Obiective pentru performanta si recuperare | Plan alimentar adaptat sportului practicat',
    'Sedinta',
    350,
    'RON',
    60,
    true,
    true,
    4
  ),
  (
    'nutritie-la-cabinet',
    'nutritie',
    'nutritie-la-cabinet-recalibrarea-raspunsului-hormonal',
    'Nutritie la cabinet RECALIBRAREA RASPUNSULUI HORMONAL',
    'Evaluare nutritionala si compozitie corporala | Explicatii despre principiile programului | Obiective si personalizare pentru perioada urmatoare',
    'Urmarire la interval de 2-3 saptamani pentru 3 luni',
    350,
    'RON',
    60,
    true,
    true,
    5
  ),
  (
    'detox-fiziologic',
    'nutritie',
    'recalibrarea-raspunsului-hormonal-detox-fiziologic',
    'RECALIBRAREA RASPUNSULUI HORMONAL - DETOX FIZIOLOGIC',
    'Program nutritie de slabire la cabinet | Monitorizare jurnal alimentar | Sedinte de stimulare metabolica Global Diagnostics',
    'Program de slabire la cabinet cu stimulare metabolica',
    3400,
    'RON',
    null,
    true,
    true,
    6
  ),
  (
    'diagnoza-metabolism',
    'nutritie',
    'diagnoza-stare-sanatate-metabolism',
    'Diagnoza stare de sanatate si a sistemelor care influenteaza METABOLISMUL',
    'Durata 90 min | Analiza metabolica si functionala | Directii de tratament si nutritie',
    'Sedinta',
    850,
    'RON',
    90,
    true,
    true,
    7
  )
on conflict (id) do update
set category_id = excluded.category_id,
    slug = excluded.slug,
    name = excluded.name,
    description = excluded.description,
    notes = excluded.notes,
    price_amount = excluded.price_amount,
    currency_code = excluded.currency_code,
    duration_minutes = excluded.duration_minutes,
    is_bookable = excluded.is_bookable,
    is_visible = excluded.is_visible,
    sort_order = excluded.sort_order,
    updated_at = timezone('utc', now());
